#!/bin/bash
echo 'Starting download'

CHOICE=$(termux-dialog radio -v "Audio,Video" -t "Download ..." | jq -r .index)

WIFI=$(termux-wifi-connectioninfo | jq -r ".supplicant_state")
if [ "$WIFI" != "COMPLETED"]; then
    CONFIRM=$(termux-dialog confirm -t "Not on Wifi" -i "Are you sure you want to continue?" | jq -r ".text")
    if [ "$CONFIRM" != "yes"]; then
        termux-notification --title "Download stopped" --content "Please reconnect to wifi and try again"
        exit(1)
    fi
fi

if [ "$CHOICE" = 0 ]; then
    youtube-dl $1
    termux-notification --title "YouTube Download" --content "Completed audio download: $1"
elif [ "$CHOICE" = 1 ]; then
    youtube-dl --config-location ~/repo/video $1
    termux-notification --title "YouTube Download" --content "Completed video download: $1"
else
    termux-notification --title "YouTube Download" --content "Failed to download: $1"
fi

