#!/bin/bash
echo 'Starting download'

CHOICE=$(termux-dialog radio -v "Audio,Video" -t "Download ..." | jq -r .index)

if [ "$CHOICE" = 0 ]; then
    youtube-dl $1
    termux-notification --title "YouTube Download" --content "Completed audio download: $1"
elif [ "$CHOICE" = 1 ]; then
    youtube-dl --config-location ~/repo/video $1
    termux-notification --title "YouTube Download" --content "Completed video download: $1"
else
    termux-notification --title "YouTube Download" --content "Failed to download: $1"
fi

